[package]
name = "llvm-sys-dylib"
version = "17.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"


[build-dependencies]
bindgen = "0.69"
